### PR TITLE
Better one-liner.

### PR DESCRIPTION
**Pull request by hemanth**
^

### CODE REVIEW

**Comment by auscompgeek** [comment]
Are git.io links read-only once created?

**Comment by hemanth** [comment]
Yes, but `https://raw.githubusercontent.com/mrowa44/emojify/master/emojify` remains constant in our case.

**Comment by auscompgeek** [comment]
My concern was security rather than the constancy of the raw download link.

**Comment by auscompgeek** [comment]
Also, uhh… the instructions you've provided don't work. I'll leave it as an activity to the reader to figure out why.

**Comment by auscompgeek** [comment]
Should also note that git.io supports HTTPS.

**Comment by hemanth** [comment]
This is just a setup script and a shorter URL will always be easy to remember

**Comment by auscompgeek** [comment]
Did you actually try doing `curl http://git.io/emojify`?

**Comment by hemanth** [comment]
Yes, we get the desired `bash` script.

**Comment by auscompgeek** [comment]
Really? Comes up blank for me. What's your curl version?

**Comment by hemanth** [comment]
```sh
$ curl --version
curl 7.37.1 (x86_64-apple-darwin14.0) libcurl/7.37.1 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM NTLM_WB SSL libz
```

**Comment by hemanth** [comment]
@mrowa44 @auscompgeek `curl -L http://git.io/emojify` work beautifully for me.

**Pull request closed without merging**
