### PR TITLE
📖 Add option to list the current emojis 📕

### PR DESCRIPTION
**Pull request by chmouel**

### CODE REVIEW

**Comment by mrowa44** [comment]
Do we really need it? I mean printing out 800+ lines of emoji doesn't seem to be really helpful for anything imo.

**Comment by chmouel** [comment]
well i pipe to less -r after, or i have to vim the file to know which one to choose

**Comment by mrowa44** [comment]
Can't you just use something like http://www.emoji-cheat-sheet.com/ ?

**Comment by chmouel** [comment]
sure,

**Pull request closed without merging**
