### PR TITLE
Add a ZSH plugin support file

### PR DESCRIPTION
**Pull request by unixorn**
* Added a zsh plugin support file so that the repo can be directly installed into their environment by ZSH framework users.
* Added instructions for loading the repo as a plugin to README.md

### CODE REVIEW

**Comment by auscompgeek** [comment]
… it's not difficult to install a single script into one's ~/bin directory…

**Comment by unixorn** [comment]
No, but it's a lot easier when you're dealing with multiple machines to let the frameworks take care of it. When I spin a new dev box in EC2 and log in for the first time, it's really nice to have zgen slurp down all my plugins automagically.

The other advantage is that the frameworks can handle periodically git pulling all the plugin repos to keep your environment current.

**Comment by auscompgeek** [comment]
Eh. All the other oh-my-zsh plugins out there (besides the cloudapp plugin) actually *need* to be a plugin, i.e. they set helper aliases for installed applications, modify the environment, chdir helpers, etc. I personally don't see how this would be useful, other than for the sake of being an oh-my-zsh plugin.

**Comment by unixorn** [comment]
My use case is that I'm already using a framework, so being able to let zgen take care of keeping my repo checkout up to date is a lot less hassle than manually downloading the script, copying it to a bindir, and periodically checking for updates to to it. Your use case is clearly different, but having a plugin.zsh file in the repository doesn't effect yours and makes mine possible.

**Pull request closed without merging**
